# Generated by Django 6.1.1 on 2026-09-07 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='chore_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('schedule__in', ['one_off', 'daily', 'weekly', 'monthly'])), name='chore_schedule_valid'),
        ),
        migrations.AddConstraint(
            model_name='chore',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'completed'])), name='chore_status_valid'),
        ),
    ]
