# Generated by Django 6.1.1 on 2026-09-07 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0003_invitecode'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chore',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_chores', to='chores.membership'),
        ),
    ]
