# Generated by Django 6.1.1 on 2026-09-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chores', '0004_chore_completed_at_chore_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='recurrence_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
